### ISSUE TITLE
License

### ISSUE THREAD

**Issue by EdorianDark** [CleverCloud/clevercloud-sdk-rust#8]
I am not sure, if AGPL is really a good license for an SDK.
I would assume, that a more permissive license like GPL would lead to more users.

**Comment by FlorentinDUBOIS** [comment]
Hi! I agree with you, I took the same license as the [sozu](https://github.com/sozu-proxy/sozu) one. I will change it to a more permissive GPL one. Thanks you for your feedback

**Comment by FlorentinDUBOIS** [comment]
The license has been updated to a less restrictive one
